name: symupy
channels:
  - licit-lab
  - conda-forge
dependencies:
  - python=3.9
  - pytest
  - coverage
  - ipython
  - symuvia=1.0.0
  - pandoc
  - sphinx
  - recommonmark
  - nbsphinx
  - sphinx-book-theme
  - ipykernel
  - pip
  - pytest
  - bump2version
  - black
  - tox
  - coverage
  - pylint
  - conda-build