{% set setup_py = load_setup_py_data() %}

package:
    name: 'symupy'
    version: {{ setup_py.get('version') }}

source:
    path: ./

requirements:
    run:
        - python=3.7
        - lxml
        - xmltodict 
        - numpy
    build:
        - python
        - setuptools

about:
    license: {{ setup_py.get('license') }}
    license_file: LICENSE
    summary: {{ setup_py.get('description') }}∫