{% set setup_py = load_setup_py_data() %}

package:
    name: 'symupy'
    version: {{ setup_py.get('version') }}

source:
    git_url: https://github.com/symuvia/symupy.git
    git_rev: 0.1.0

build: 
    number: 0

requirements:
    run:
        - python=3.7
        - lxml
        - xmltodict 
        - numpy>=1.16
    build:
        - python
        - setuptools

test:
    imports: 
        - symupy

about:
    license: {{ setup_py.get('license') }}
    license_file: LICENSE
    summary: {{ setup_py.get('description') }}∫