{% set setup_py = load_setup_py_data() %}

package:
    name: symupy
    version: {{ setup_py.get('version') }}

source:
    path: ../

build:
  preserve_egg_dir: True
  number: 0
  script: "python -m pip install . -vv"

requirements:
  build:
    - python=3.9
    - setuptools
  run:
    - python=3.9
    - numpy>=1.16
    - lxml>=4.3.3
    - networkx>=2.5
    - matplotlib>=3.0.0
    - sqlalchemy>=1.3.5
    - pandas>=1.0.0
    - scipy>=1.4.1
    - click>=7.0
    - python-decouple>=3.3
    - ipython
    - symuflow=1.1.0
    - pyqt
    - pyqtgraph

test:
  requires:
    - pytest
    - coverage
  commands:
    - pytest -v tests
  source_files:
    - tests/

about:
  license: MIT
  license_file: LICENSE.md
  summary: {{ setup_py.get('description') }}
