{% set setup_py = load_setup_py_data() %}

package:
    name: 'symupy'
    version: {{ setup_py.get('version') }}

source:
    path: ../

build:
  preserve_egg_dir: True
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0)}}

requirements:
    build:
        - python=3.9
        - setuptools
    host:
        - python=3.9
        - setuptools
    run:
        - python=3.9
        - numpy>=1.16
        - lxml>=4.3.3
        - xmltodict>=0.12
        - networkx>=2.5
        - matplotlib>=3.0.0
        - sqlalchemy>=1.3.5
        - pandas>=1.0.0
        - scipy>=1.4.1
        - click>=7.0
        - python-decouple>=3.3
        - ipython
        - symuvia=1.0.0

test:
    requires:
        - pytest
        - coverage
    imports:
        - symupy
    sorce_files:
        - tests/metaclass/test*.py
        - tests/reader/test*.py
        - tests/runtime/test*.py
        - tests/tsc/test*.py
        - tests/utils/test*.py
        - tests/mocks/*.xml
        - tests/mocks/*.xml

    commands:
        - python -m pytest tests/metaclass
        - python -m pytest tests/preprocess
        - python -m pytest tests/runtime
        - python -m pytest tests/tsc
        - python -m pytest tests/utils
about:
    license: {{ setup_py.get('license') }}
    license_file: LICENSE
    summary: {{ setup_py.get('description') }}
