name: symupy
channels:
  - licit-lab
  - conda-forge
dependencies:
  - python=3.9
  - pandoc==1.0.2
  - sphinx==3.2.1
  - recommonmark==0.6.0
  - sphinx-rtd-theme==0.5.0
  - nbsphinx==0.8.1
  - pandoc==1.0.2
  - sphinx-book-theme
  - ipykernel
  - numpy>=1.16
  - lxml>=4.3.3
  - xmltodict>=0.12
  - networkx>=2.5
  - matplotlib>=3.0.0
  - sqlalchemy>=1.3.5
  - pandas>=1.0.0
  - scipy>=1.4.1
  - click>=7.0
  - python-decouple>=3.3
  - pytest
  - coverage
  - ipython
  - symuvia=1.0.0
