name: symupy_doc
channels:
  - licit-lab
  - conda-forge
  - anaconda
dependencies:
  - python=3.9
  - pandoc
  - sphinx
  - recommonmark
  - anaconda::sphinx-rtd-theme
  - nbsphinx
  - sphinx-book-theme
  - ipykernel
  - numpy>=1.16
  - lxml>=4.3.3
  - xmltodict>=0.12
  - networkx>=2.5
  - matplotlib>=3.0.0
  - sqlalchemy>=1.3.5
  - pandas>=1.0.0
  - scipy>=1.4.1
  - click>=7.0
  - python-decouple>=3.3
  - pytest
  - coverage
  - ipython
  - symuvia=1.0.0
