name: conda build

on:
  push:
    branches:
      - develop

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: build
        run: |
          $CONDA/bin/conda update -n base -c defaults conda
          $CONDA/bin/conda install conda-build anaconda-client conda-verify
          mkdir conda-bld
          $CONDA/bin/conda build . -c licit-lab -c conda-forge --output-folder conda-bld/
